// Code generated by "stringer -type=Type"; DO NOT EDIT

package token

import "fmt"

const _Type_name = "ILLEGALEOFIDENTINTSTRINGSYMBOLASSIGNPLUSMINUSBANGASTERISKSLASHLTGTEQNOTEQNEWLINECOMMASEMICOLONDOTCOLONLPARENRPARENLBRACERBRACELBRACKETRBRACKETDEFSELFENDIFTHENELSETRUEFALSERETURNNIL"

var _Type_index = [...]uint8{0, 7, 10, 15, 18, 24, 30, 36, 40, 45, 49, 57, 62, 64, 66, 68, 73, 80, 85, 94, 97, 102, 108, 114, 120, 126, 134, 142, 145, 149, 152, 154, 158, 162, 166, 171, 177, 180}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
