// Code generated by "stringer -type=Type"; DO NOT EDIT.

package token

import "fmt"

const _Type_name = "ILLEGALEOFIDENTCONSTGLOBALINTSTRINGSYMBOLASSIGNPLUSMINUSBANGASTERISKSLASHLTGTEQNOTEQNEWLINECOMMASEMICOLONDOTCOLONLPARENRPARENLBRACERBRACELBRACKETRBRACKETPIPESCOPEDEFSELFENDIFTHENELSETRUEFALSERETURNNILMODULECLASSDOYIELD"

var _Type_index = [...]uint8{0, 7, 10, 15, 20, 26, 29, 35, 41, 47, 51, 56, 60, 68, 73, 75, 77, 79, 84, 91, 96, 105, 108, 113, 119, 125, 131, 137, 145, 153, 157, 162, 165, 169, 172, 174, 178, 182, 186, 191, 197, 200, 206, 211, 213, 218}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
